Framework task
Kubiken/SomeCode pull request #2
Opened 2018-04-15 19:38 UTC by Kubiken

Добавил таблицу с типами, репозиторий и контекст сделал шаблонами.

2018-04-16 10:04 UTC, troepolik commented
уже ближе к истине, но:
1)Зачем тебе наследник - класс AppContext ? в DbContext уже итак находятся все необходимые для тебя шаблонные методы и свойства. например Set<T>  или как-то так, позволяет вернуть дбсет с нужным типом.
2) Вот этот метод очень плох:
public List<T> ReturnList()
+        {
+            return Context.List.ToList();
+        }
это посути возврат всегда всей таблицы. а если она большая?
где старые добрые методы загрузки по linq ? 
3) вот это нафиг не нужно:
sr.ModifyState(SelectedItem);
EF  сам понимает что объект изменен, если ты его меняешь , неотсоединяя от контекста, а ты не отсоединяешь.
4) опять у тебя в гит попали какие-то служебные файлы, которых там не должно быть
fmwtask/fmwtask/obj/Debug/fmwtask_MarkupCompile.i.cache
делетни их и поставь в игнор

5) метод public void Retrieve() делает какую-то муру...
я чет сомневаюсь что это отменяет все сделанные над объектом изменения.
например если я на форме поменяю название твоему объекту, но не сохраню, при нажатии "отмена" название вернется в первоначальное состояние?

2018-04-16 11:53 UTC, Kubiken commented
Насчет пятого да, если до нажатия "сохранить" сделать отмену, все вернется к первоначальному. Каждый раз будет откатывать или к первоначальному состояния или к последнему сейву, если он был. 16.04.2018, 13:04, "Aleksey Troepolskiy" <notifications@github.com>:уже ближе к истине, но:
1)Зачем тебе наследник - класс AppContext ? в DbContext уже итак находятся все необходимые для тебя шаблонные методы и свойства. например Set  или как-то так, позволяет вернуть дбсет с нужным типом.
2) Вот этот метод очень плох:
public List ReturnList()


   {



       return Context.List.ToList();



   }



это посути возврат всегда всей таблицы. а если она большая?
где старые добрые методы загрузки по linq ?
3) вот это нафиг не нужно:
sr.ModifyState(SelectedItem);
EF  сам понимает что объект изменен, если ты его меняешь , неотсоединяя от контекста, а ты не отсоединяешь.
4) опять у тебя в гит попали какие-то служебные файлы, которых там не должно быть
fmwtask/fmwtask/obj/Debug/fmwtask_MarkupCompile.i.cache
делетни их и поставь в игнор

метод public void Retrieve() делает какую-то муру...
я чет сомневаюсь что это отменяет все сделанные над объектом изменения.
например если я на форме поменяю название твоему объекту, но не сохраню, при нажатии "отмена" название вернется в первоначальное состояние?


—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

2018-04-16 13:17 UTC, Kubiken commented
Еще вопрос: точно нужно переделывать первый пункт? Программа так структурированее как по мне, да и сами мелкомягкие советуют создавть наследника DbContext, а не работать с родителем https://msdn.microsoft.com/en-us/library/jj729737(v=vs.113).aspx16.04.2018, 13:04, "Aleksey Troepolskiy" <notifications@github.com>:уже ближе к истине, но:
1)Зачем тебе наследник - класс AppContext ? в DbContext уже итак находятся все необходимые для тебя шаблонные методы и свойства. например Set  или как-то так, позволяет вернуть дбсет с нужным типом.
2) Вот этот метод очень плох:
public List ReturnList()


   {



       return Context.List.ToList();



   }



это посути возврат всегда всей таблицы. а если она большая?
где старые добрые методы загрузки по linq ?
3) вот это нафиг не нужно:
sr.ModifyState(SelectedItem);
EF  сам понимает что объект изменен, если ты его меняешь , неотсоединяя от контекста, а ты не отсоединяешь.
4) опять у тебя в гит попали какие-то служебные файлы, которых там не должно быть
fmwtask/fmwtask/obj/Debug/fmwtask_MarkupCompile.i.cache
делетни их и поставь в игнор

метод public void Retrieve() делает какую-то муру...
я чет сомневаюсь что это отменяет все сделанные над объектом изменения.
например если я на форме поменяю название твоему объекту, но не сохраню, при нажатии "отмена" название вернется в первоначальное состояние?


—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

2018-04-19 11:39 UTC, troepolik requested changes

2018-04-19 11:39 UTC, troepolik commented on fmwtask/fmwtask/DbStuff/SQLiteRepos.cs
> +            ToList = Context.List.ToList();
Не, чувак это какой-то бред, я не понимаю что творится у тебя в голове)
По сути ты делаешь слив всей таблицы в список и далее работаешь с этим списком. А если бд что-то поменяется?
Убери public List<T> ReturnList(), его быть не должно.
Открой свой старый репозиторий, где вы работали через ADO,  копируй сигнатуры методов, они не должны поменяться (это было в задании, черт возьми!) и реализуй их здесь. Таким образом там была загрузка по sql  и еще какой-то вид загрузки ,Не помню, кажется по linq, DBContext  все это умеет делать тебе останется делегировать это ему вместо ADO  как было раньше

2018-04-24 20:49 UTC, Kubiken commented on fmwtask/fmwtask/DbStuff/SQLiteRepos.cs
> +            ToList = Context.List.ToList();
Не совсем понимаю чего вы хотите. Метод Load из старого проекта открывал коннект, забивал бд в лист, закрывал коннект и возвращал этот самый лист, т.е. то же самое, что вы просите поменять в этом проекте. Метод LoadByLinq был, он нужен был для получения элементов с определенными критериями из бд, но никаких специфичных запросов в этом проекте нет.

2018-04-24 20:53 UTC, Kubiken commented on fmwtask/fmwtask/DbStuff/SQLiteRepos.cs
> +            ToList = Context.List.ToList();
Олсо метод который вам не нравится убрал, загружаю так: sr.Context.List.ToList<Gun>() (хоть это вроде как и противоречит пункту о том, что на VM должны быть только Репозиторий и его методы).

2018-04-25 06:33 UTC, troepolik requested changes

2018-04-25 06:33 UTC, troepolik commented on fmwtask/fmwtask/DbStuff/SQLiteRepos.cs
> +        public AppContext<T> Context;
public AppContext<T> Context;
опять контекст публичный?
это значит вся приложуха опять завязана на EF ? 
я в который раз говорю : реализуй методы которые были в старом ADO  репозитории (загрузка по sql  и загрузка по Linq), просто юзай вместо ADO  свой Context

2018-04-25 15:40 UTC, Kubiken commented
Реализовал функции из предыдущего проекта (Load, LoadById, LoadByLinq). Работают напрямую с бд, если надо добавлю кэш.

2018-04-26 06:51 UTC, troepolik requested changes

2018-04-26 06:51 UTC, troepolik commented on fmwtask/fmwtask/DbStuff/SQLiteRepos.cs
> +            var obj = Context.List.Where<T>(c => c.Id == id);
var obj = Context.List.Where<T>(c => c.Id == id);
+            return (T)obj;
это работать не будет, удивлен что вообще скомпилировалось.
Where возвращает перечисление. Тебе нужно заюзать что-то типа FirstOrDefault вместо Where

2018-04-26 06:51 UTC, troepolik commented on fmwtask/fmwtask/DbStuff/SQLiteRepos.cs
> +            var subres = Context.List.Where(filter);
можно написать компактнее, в одну строчку:
return Context.List.Where(filter).ToList();

2018-04-27 07:53 UTC, troepolik approved these changes

2018-04-27 07:53 UTC, merged